In [42]:
import numpy as np

a = np.random.randn(5)

In [43]:
print(a)

[ 1.71435802 -0.12453887  1.04031096 -0.02025591  1.06578031]


In [44]:
print(a.shape)


(5,)


In [45]:
print(a.T)

[ 1.71435802 -0.12453887  1.04031096 -0.02025591  1.06578031]


In [46]:
print(np.dot(a,a.T))

5.17307821589362


In [47]:
a = np.random.randn(5,1)
print(a)

[[ 1.76639447]
 [-0.38106645]
 [-0.82352551]
 [ 0.92218235]
 [ 0.02353164]]


In [48]:
print(a.T)

[[ 1.76639447 -0.38106645 -0.82352551  0.92218235  0.02353164]]


In [49]:
print(np.dot(a,a.T))

[[ 3.12014942e+00 -6.73113675e-01 -1.45467091e+00  1.62893780e+00
   4.15661554e-02]
 [-6.73113675e-01  1.45211642e-01  3.13817945e-01 -3.51412756e-01
  -8.96711786e-03]
 [-1.45467091e+00  3.13817945e-01  6.78194266e-01 -7.59440688e-01
  -1.93789043e-02]
 [ 1.62893780e+00 -3.51412756e-01 -7.59440688e-01  8.50420280e-01
   2.17004612e-02]
 [ 4.15661554e-02 -8.96711786e-03 -1.93789043e-02  2.17004612e-02
   5.53737992e-04]]


In [50]:
assert(a.shape == (5,1))
